// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

// T(c)=o(n)
// space=o(1)
class FindDifference
{
    static char findDiff(String s,String t)
    {
        int a[]=new int[256];
        int i=0;
        int j=0;
        if(s.length()==0)
        return t.charAt(0);
        
        while(i<s.length() || j<t.length())
        {
            if(j<t.length())
            {
                a[t.charAt(j)]++;
            }
            if(i<s.length())
            {
                a[s.charAt(i)]--;
            }
            i++;
            j++;
        }
        char c=0;
        for(i=0;i<a.length;i++)
        {
            if(a[i]!=0)
            c=(char)i;
        }
        return c;
    }
    public static void main(String args[])
    {
        String s = "abcd";
        String t = "abcde";
        System.out.println("Difference char is:"+findDiff(s,t));
    }
}